import { gql } from '@apollo/client'
import Container from '@components/Container'
import Layout from '@components/Layout'
import styles from '@styles/Page.module.scss'
import Head from 'next/head'
import { FaExternalLinkAlt } from 'react-icons/fa'
import { apolloClient } from 'src/clients/apollo'

export default function Stores({ storeLocations }) {
  console.log('🚀 ~ storeLocations', storeLocations)

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <h1>Locations</h1>

        <div className={styles.stores}>
          <div className={styles.storesLocations}>
            <ul className={styles.locations}>
              {storeLocations.map(
                ({ id, name, address, phoneNumber, location }) => (
                  <li key={id}>
                    <p className={styles.locationName}>{name}</p>
                    <address>{address}</address>
                    <p>{phoneNumber}</p>
                    <p className={styles.locationDiscovery}>
                      <button>View on Map</button>
                      <a
                        href={`https://www.google.com/maps/dir//${location.latitude},${location.longitude}/@${location.latitude},${location.longitude},14z`}
                        target="_blank"
                        rel="noreferrer"
                      >
                        Get Directions
                        <FaExternalLinkAlt />
                      </a>
                    </p>
                  </li>
                )
              )}
            </ul>
          </div>

          <div className={styles.storesMap}>
            <div className={styles.storesMapContainer}>
              <div className={styles.map}>Map</div>
            </div>
          </div>
        </div>
      </Container>
    </Layout>
  )
}

export async function getStaticProps() {
  const { data } = await apolloClient.query({
    query: gql`
      query PageStores {
        storeLocations {
          id
          address
          name
          phoneNumber
          location {
            latitude
            longitude
          }
        }
      }
    `,
  })

  const { storeLocations } = data

  return {
    props: {
      storeLocations,
    },
  }
}
